# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180110_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.TextField(default=''),
        ),
    ]
